<?php
/**
 * Created by PhpStorm.
 * User: Сергей
 * Date: 13.09.2019
 * Time: 9:48
 */
//Работа с переменными
echo ("Задание 1");
echo "<br>";
$a=3;
$b=$a;
echo $b;
echo "<br>";
echo ("Задание 2");
echo "<br>";
$a=10;
$b=2;
echo ($a+$b)/(($a+$b)/2);
echo "<br>";
echo ($a-$b)/(($a+$b)/2);
echo "<br>";
echo ($a*$b)/(($a+$b)/2);
echo "<br>";
echo ($a/$b)/(($a+$b)/2);
echo "<br>";
echo ("Задание 3");
echo "<br>";
$c=15;
$d=2;
$result=$c+$d;
echo $result;
echo "<br>";
echo ("Задание 4");
echo "<br>";
$a=10;
$b=2;
$c=5;
echo ($a+$b+$c)/(($a+$b+$c)/3);
echo "<br>";
echo ("Задание 5");
echo "<br>";
$a=17;
$b=10;
$c=$a-$b;
$d=17;
$result=$c+$d;
echo $result;
//Работа со строками
echo "<br>";
echo ("Задание 1.2");
echo "<br>";
$text='Привет, мир!';
echo $text."Моя первая программа!";
echo "<br>";
echo ("Задание 2.2");
echo "<br>";
$text1='Привет';
$text2='Мир!';
echo ($text1.$text2);
echo "<br>";
echo ("Задание 3.2");
echo "<br>";
$name="Сергей";
echo "Привет,".$name;
$text="Новый текст";
echo "<br>";
echo ("Задание 4.2");
echo "<br>";
$age="18";
$height="182";
echo 'Мой возраст:'.$age."|".'Мой рост:'.$height;
//Работа с массивами
echo "<br>";
echo ("Задание 1.3");
echo "<br>";
$arr=['a','b','c'];
var_dump($arr);
echo "<br>";
var_dump($arr[0]);
echo "<br>";
var_dump($arr[1]);
echo "<br>";
var_dump($arr[2]);
echo "<br>";
echo ("Задание 2.3");
echo "<br>";
$arr=['a','b','c'];
echo $arr[0].$arr[1].$arr[2];
echo "<br>";
echo ("Задание 3.3");
echo "<br>";
$arr=['a','b','c','d'];
echo $arr[0].'+'.$arr[1];
echo "<br>";
echo $arr[2].'+'.$arr[3];
echo "<br>";
echo $arr[0].'-'.$arr[3];
echo "<br>";
echo $arr[0].'/'.$arr[3];
echo "<br>";
echo ("Задание 4.3");
echo "<br>";
$arr=[2,5,3,9];
$result=($arr[0]*$arr[1])+($arr[2]*$arr[3]);
echo $result;
echo "<br>";
echo ("Задание 5.3");
echo "<br>";
$arr[10]=1;
$arr[20]=2;
$arr[30]=3;
$arr[40]=4;
$arr[50]=5;
echo $arr[20];
//Ассоциативные массивы
echo "<br>";
echo ("Задание 1.4");
echo "<br>";
$arr=['a'=>11, 'b'=>20, 'c'=>30];
echo $arr['c'];
echo "<br>";
echo $arr['a']+$arr['b']+$arr['c'];
echo "<br>";
echo ("Задание 2.4");
echo "<br>";
$arr=['q3'=>12, 'r3'=>23, 'f3'=>34];
echo $arr['q3']+$arr['r3']+$arr['f3'];
echo "<br>";
echo ("Задание 3.4");
echo "<br>";
$arr=['Коля'=>'1000$', 'Вася'=>'500$', 'Петя'=>'200$'];
echo "Петя:".$arr['Петя']."<br>"."Коля:".$arr['Коля'];
echo "<br>";
echo ("Задание 4.4");
echo "<br>";
$arr=['1'=>'Январь','2'=>'Февраль','3'=>'Март','4'=>'Апрель','5'=>'Май','6'=>'Июнь','7'=>'Июль','8'=>'Август','9'=>'Сентябрь','10'=>'Октябрь','11'=>'Ноябрь','12'=>'Декабрь'];
echo  $arr['9'].'-'.$arr['6'];
echo "<br>";
echo ("Задание 5.4");
echo "<br>";
$arr=['1'=>'понед','2'=>'вторник','3'=>'среда','4'=>'четверг','5'=>'пятн','6'=>'субб','7'=>'воскр'];
echo $arr['3'];